#!/usr/bin/env python3
"""Writes docs/ui-contract.md: for every UI test (tests/Browser/{Admin,User,Guest}), the pages it visits, the selectors it uses and the texts
it asserts, i.e. what another implementation of the site (Celestia) has to render for the test to pass. Re-run after changing the UI tests."""
import re, glob, os, collections

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = ["# UI contract (generated by scripts/generate-ui-contract.py)", "",
       "What each Winterchilla UI test needs from the site under test. Run them against another implementation with",
       "`UI_BASE_URL=<origin> vendor/bin/pest tests/Browser/Admin tests/Browser/User tests/Browser/Guest --exclude-group=winterchilla-only`.",
       "Selectors are CSS (`#id`, `[data-testid=...]`); `see` lists visible-text assertions; paths are what the test navigates to (`{...}` are seeded IDs).", ""]
sel_usage = collections.Counter(); testids = collections.Counter(); ids = collections.Counter(); paths = collections.Counter()

def clean(v):
    v = v.replace("TestSeederConstants::loginUrl(", "login as ").replace("TestSeederConstants::", "").replace("$base . ", "")
    v = re.sub(r"'\s*\.\s*([^'.]+?)\s*(?:\.\s*'|$)", lambda m: "{" + m.group(1).strip("() ") + "}", v)
    return v.strip("'\" )")

for d in ('Guest', 'User', 'Admin'):
    for f in sorted(glob.glob(f'{root}/tests/Browser/{d}/*.php')):
        src = open(f).read()
        file_only = "uses()->group('winterchilla-only')" in src
        out.append(f"## {d}/{os.path.basename(f)}" + ("  (winterchilla-only)" if file_only else "")); out.append("")
        blocks = re.split(r"\n(?=it\()", src)
        for b in blocks:
            m = re.match(r"it\('((?:[^'\\]|\\.)*)'", b)
            if not m: continue
            only = file_only or "->group('winterchilla-only')" in b
            name = m.group(1).replace("\\'", "'")
            body = b
            pp = re.findall(r"(?:visit|navigate|goto)\(\s*(.*?)\)(?=\s*(?:->|;|\n))", body)
            pp = [clean(p) for p in pp if "base" in p or "loginUrl" in p or p.startswith("'/")]
            sels = re.findall(r"->(?:click|assertVisible|assertPresent|assertMissing|assertNotPresent|fill|type|select|check|attach|assertSeeIn|assertDontSeeIn|assertValue|press|hover)\(\s*'((?:[^'\\]|\\.)*)'", body)
            sees = re.findall(r"->assert(?:See|SeeIn|DontSee|DontSeeIn)\(\s*(?:'(?:[^'\\]|\\.)*'\s*,\s*)?'((?:[^'\\]|\\.)*)'", body)
            for s_ in sels:
                sel_usage[s_] += 1
                for t in re.findall(r"data-testid=['\"]?([\w-]+)", s_): testids[t] += 1
                for i in re.findall(r"#([\w-]+)", s_): ids[i] += 1
            for p in pp: paths[p] += 1
            out.append(f"- **{name}**" + ("  _(winterchilla-only)_" if only else ""))
            if pp: out.append("  - paths: " + ", ".join(f"`{p}`" for p in dict.fromkeys(pp)))
            if sels: out.append("  - selectors: " + ", ".join(f"`{s}`" for s in dict.fromkeys(sels)))
            if sees: out.append("  - see: " + ", ".join(f"“{s}”" for s in dict.fromkeys(sees)))
        out.append("")
out += ["## Summary", "", f"- `data-testid` values used ({len(testids)}): " + ", ".join(f"`{t}`" for t in sorted(testids)), "",
        f"- element ids used ({len(ids)}): " + ", ".join(f"`#{i}`" for i in sorted(ids)), ""]
open(f'{root}/docs/ui-contract.md', 'w').write("\n".join(out) + "\n")
print(len(testids), "testids,", len(ids), "ids")
