<?php

namespace App\Controllers;

use App\CoreUtils;

class DocsController extends Controller {
  public function index() {
    CoreUtils::removeCSPHeaders();
    // Generated by the deploy (and by scripts/generate_api_schema.php); regenerating on every visit takes seconds
    CoreUtils::generateApiSchema(true);
    CoreUtils::loadPage(__METHOD__);
  }
}
